feat: on hover award name tooltip
Etimo/etimo-achievements pull request #336
Opened 2022-08-02 12:25 UTC by elmaxe

Denna PR gör så att ett achievements beskrivning kommer upp som tooltip när man hoovrar på achievement-namnet i award list.

Lade till support för cell-tooltips i `PaginatedTable`

2022-08-04 11:51 UTC, niclaslindstedt requested changes

2022-08-04 11:51 UTC, niclaslindstedt commented on packages/web/src/components/table/TableCell.tsx
> +// import { Tooltip } from '@mui/material';
Varför är den här utkommenterade raden här?

2022-08-04 12:23 UTC, elmaxe commented on packages/web/src/components/table/TableCell.tsx
> +// import { Tooltip } from '@mui/material';
Satt och rebase:ade fram och tillbaka för att fixa en grej, slank igenom på något sätt

2022-08-10 08:50 UTC, niclaslindstedt approved these changes

2022-08-10 11:50 UTC, merged